# Database Configuration
database:
  host: 127.0.0.1
  port: 5432
  user: ridehail_user
  password: ridehail_pass
  database: ridehail_db

# RabbitMQ Configuration
rabbitmq:
  host: 127.0.0.1
  port: 5672
  user: guest
  password: guest

# WebSocket Configuration
websocket:
  port: 8080

# Service Ports
services:
  ride_service: 3000
  driver_location_service: 3001
  admin_service: 3004

# Secret Key
jwt:
  secret_key: "q83JkP8zB5T!pD@4R1mX2yN7sV9fG0wH"
